### ISSUE TITLE
Dependecy conflict on angular 12

### ISSUE THREAD

**Issue by sumzer** [nglrx/pipes#42]
**Describe the bug**
error occurs upon installation of package

**To Reproduce**
run `npm i @nglrx/pipes`

**Expected behavior**
package should be installed without problems

**Screenshots/Error**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fe-cms-cf@0.0.0
npm ERR! Found: @angular/core@12.0.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0" from @nglrx/pipes@0.5.1
npm ERR! node_modules/@nglrx/pipes
npm ERR!   @nglrx/pipes@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kneurgao** [comment]
@sumzer Let me check this.

**Comment by kneurgao** [comment]
@sumzer Peer dependencies have been updated. Angular version now supported till v12

Install latest version (0.7.0) of `@nglrx/pipes` via npm

`
npm i @nglrx/pipes@0.7.0
`

For more details check https://www.npmjs.com/package/@nglrx/pipes

For releases check https://github.com/nglrx/pipes/releases

Kindly let me know your feedback.
