### ISSUE TITLE
Angular 14/15/16 version

### ISSUE THREAD

**Issue by bertheto** [nglrx/pipes#76]
Hello, Could you publish a version compatible with recent versions of Angular please ? (14/15/16/)

Thanks in advance

Olivier

**Comment by kneurgao** [comment]
Sure, will plan for the same soon

**Comment by kneurgao** [comment]
Added support for Angular versions 14, 15 and 16 in [v0.9.1](https://www.npmjs.com/package/@nglrx/pipes/v/0.9.1)
Please take a look and let me know in case of any issues.

**Comment by bertheto** [comment]
Hi, 
Thank you !
regards
Olivier
